# Generated by Django 4.1.7 on 2023-04-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='SensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor', unique=True),
        ),
    ]
