# Generated by Django 4.1.7 on 2023-04-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_mapping_sensorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='status',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
