# Generated by Django 4.1.7 on 2023-03-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.AlterField(
            model_name='user',
            name='mob_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
